export const blogsContent = [
  {
    id: 1,
    title: "Working with legacy stacks",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "April 07, 2021",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&q=75&fit=crop&w=600",
    type: "featured",
    slug: "working-with-legacy-stacks",
  },
  {
    id: 2,
    title: "10 best smartphones for devs",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "March 15, 2021",
    image: "https://images.unsplash.com/photo-1542759564-7ccbb6ac450a?auto=format&q=75&fit=crop&w=600",
    type: "featured",
    slug: "10-best-smartphones-for-devs",
  },
  {
    id: 3,
    title: "8 High performance Notebooks",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "January 27, 2021",
    image: "https://images.unsplash.com/photo-1610465299996-30f240ac2b1c?auto=format&q=75&fit=crop&w=600",
    type: "featured",
    slug: "8-high-performance-notebooks",
  },
  {
    id: 4,
    title: "New trends in Tech",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "July 19, 2021",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&q=75&fit=crop&w=600",
    type: "recent",
    slug: "new-trends-in-tech",
  },
  {
    id: 5,
    title: "Working with legacy stacks",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "July 19, 2021",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&q=75&fit=crop&w=600",
    type: "recent",
    slug: "working-with-legacy-stacks",
  },
  {
    id: 6,
    title: "10 best smartphones for devs",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "March 15, 2021",
    image: "https://images.unsplash.com/photo-1542759564-7ccbb6ac450a?auto=format&q=75&fit=crop&w=600",
    type: "recent",
    slug: "10-best-smartphones-for-devs",
  },
  {
    id: 7,
    title: "8 High performance Notebooks",
    description: "This is a section of some simple filler text, also known as placeholder text.",
    postedOn: "January 27, 2021",
    image: "https://images.unsplash.com/photo-1610465299996-30f240ac2b1c?auto=format&q=75&fit=crop&w=600",
    type: "recent",
    slug: "8-high-performance-notebooks",
  }
];